### ISSUE TITLE
Having exception before editing a script 

### ISSUE THREAD

**Issue by Pinkii-** [josec89/wakatime-unity#2]
Hello there! Thanks so much for your effort!

I'm trying your wakatime plugin and I'm getting tons of exceptions when I'm trying to execute the program after modifying any script.

All the errors are like this:
`Missing built-in guistyle ColorPickerBox
System.Diagnostics.Process:Start()
WakaTime.PythonManager:TryGetPathFromFixedPath() (at Assets/Editor/WakaTime/PythonManager.cs:109)
WakaTime.PythonManager:GetPythonPath() (at Assets/Editor/WakaTime/PythonManager.cs:22)
WakaTime.PythonManager:IsPythonInstalled() (at Assets/Editor/WakaTime/PythonManager.cs:13)
WakaTime.Main:.cctor() (at Assets/Editor/WakaTime/Main.cs:26)
UnityEditor.EditorAssemblies:SetLoadedEditorAssemblies(Assembly[])`

I had like 60 exception of the same type: Missing built-in guistyle GUITHING (for example: BoldLabel, LargeLabel, etc.), and continuing these errors I have null pointer exceptions ( I suppose that is because when you try to initialize some GUI things, the program cant find them and later is trying to access to them)

![wakaTimeErrors](https://cloud.githubusercontent.com/assets/4028884/8460870/788cd7f8-2028-11e5-8281-a73d372a954f.png)

I'm pretty new for Unity so if the problem is that I'm a noob, let me know how to fix it please :D

If you want I can try to upload a pastebin or something like this with the all errors in a couple of days (I'm staying in a island with a very bad connection).

Thanks for your work and let me know if I can help!
Cheers,
Pinkii

**Comment by josec89** [comment]
Hello! Thanks for testing,

What system are you using? Windows is still quite buggy. 
Did you have Python already installed? Otherwise, did the Install shield run and successfully installed Python? Where is python installed (if it is): something like C:/Python XX/python.exe?

I've been busy some days but I'm already back to the development and I'll check this!

Thanks again, and No: it's not your fault for being noob or wathever! :D
Regards.

**Comment by Pinkii-** [comment]
I'm using Windows and I have Python34 installed at the C: directory and i have the executable of python.

I'm going to try your new version and as soon as possible give you feedback.

Thanks!

**Comment by Pinkii-** [comment]
I had no more errors like this.

Thanks for fix it!
