### ISSUE TITLE
Not logging data from Unity.

### ISSUE THREAD

**Issue by Ashwinning** [josec89/wakatime-unity#3]
Installed Unity plugin two days ago, python installed fine & I entered my API key.

However, no data is being logged to WakaTime from Unity, other IDEs are working fine.

Enabled the WakaTime debug in Unity, and the logs seem to be fine.
![](https://i.gyazo.com/2550e3a3b83094ad3952415c02fe1cdf.png)

**Comment by josec89** [comment]
The wakatime-client version was old, I updated the client to the current version, it should be working now. Please check it and let me now if it's still failing. https://wakatime.com/api/v1/users/current Use this url to check the last heartbeat.

Thanks.

**Comment by Ashwinning** [comment]
Works perfectly!
Thanks!
