### ISSUE TITLE
Not woring with Unity3D on Linux

### ISSUE THREAD

**Issue by WBad** [josec89/wakatime-unity#5]
It pops up the enter API key dialog then once you click no other window is open.
I would be willing to manually add my API key to the settings files if I knew where their stored?

http://forum.unity3d.com/threads/unity-on-linux-release-notes-and-known-issues.350256

**Comment by josec89** [comment]
The settings windows should be opened. Can you try to open the window manually?
On the top bar --> Window / Wakatime
 I haven't tested on Linux :(

**Comment by WBad** [comment]
WOW Quick response.
Yes manually opening the dialog works, thanks.
It seems to be working now.

**Comment by josec89** [comment]
Could you confirm it is working on Linux so I can close this issue? 
Thanks :)

**Comment by WBad** [comment]
Works once you manually open the dialog, thanks.
