### ISSUE TITLE
Dashboard not updating in Unity 5.4

### ISSUE THREAD

**Issue by aCallum** [josec89/wakatime-unity#7]
Attempting to run in unity 5.4. Have updated WakaTime client to latest (6.2.0) with no success.

**Comment by josec89** [comment]
@aCallum Sorry I don't have time to support this plugin, if you find the error and publish a PR I will approve it and the community will love you --> there is a slack for wakatime maybe you could try to contact there with wakatime devs if you have any questions 

Thanks for your help ^^

**Comment by alanhamlett** [comment]
Fixed with #8 and #9. Thanks @aCallum!
